"""empty message

Revision ID: f2e1ed0473d0
Revises: a5cffa318ac2
Create Date: 2025-04-10 01:09:06.087645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e1ed0473d0'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('nombre_de_usuario', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=False),
    sa.Column('apellido', sa.String(length=15), nullable=False),
    sa.Column('correo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ID', 'correo'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('nombre_de_usuario')
    )
    op.create_table('Comentario',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('texto_comentario', sa.String(length=200), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['Usuario.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Comentario')
    op.drop_table('Usuario')
    # ### end Alembic commands ###
